---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-sync-operator
  namespace: default
imagePullSecrets:
- name: bluemix-default-secret
- name: bluemix-default-secret-regional
- name: bluemix-default-secret-international
- name: default-icr-io
- name: default-us-icr-io
- name: default-uk-icr-io
- name: default-de-icr-io
- name: default-au-icr-io
- name: default-jp-icr-io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secret-sync-operator
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["namespaces", "pods", "replicasets"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secret-sync-operator
subjects:
- kind: ServiceAccount
  name: secret-sync-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: secret-sync-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-sync-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: secret-sync-operator
  template:
    metadata:
      labels:
        name: secret-sync-operator
    spec:
      serviceAccountName: secret-sync-operator
      containers:
        - name: secret-sync-operator
          image: <REPLACE WITH YOUR BUILT IMAGE NAME>
          command:
          - secret-sync-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: OPERATOR_NAME
              value: "secret-sync-operator"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
